// src/proto.rs — Protobuf contract bridge
//
// This module pulls in the Rust structs generated by `prost-build` at compile
// time. The generated file lives in $OUT_DIR (managed by Cargo) and is never
// committed to source control.
//
// Usage inside other modules:
//   use crate::proto::market_data::Tick;

/// Generated Protobuf types for the `ai_trade.market_data` package.
/// Exposes: `Tick` — the canonical real-time tick message used across the
/// entire pipeline (Kafka topic: `market.ticks`).
#[allow(dead_code)]
pub mod market_data {
    include!(concat!(env!("OUT_DIR"), "/ai_trade.market_data.rs"));
}
